-- MySQL Script generated by MySQL Workbench
-- Mon Apr 17 16:04:39 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema aim
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aim
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aim` DEFAULT CHARACTER SET utf8 ;
USE `aim` ;

-- -----------------------------------------------------
-- Table `aim`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aim`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(25) NOT NULL,
  `password` VARCHAR(25) NOT NULL,
  `solved` INT NULL DEFAULT 0,
  `failed` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aim`.`user_aim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aim`.`user_aim` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(300) NULL DEFAULT 'Empty aim',
  `control` VARCHAR(400) NULL DEFAULT NULL,
  `deadline` DATE NULL,
  `archive` TINYINT(1) NULL DEFAULT 0,
  `result` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_aim_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_user_aim_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `aim`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aim`.`user_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aim`.`user_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NULL,
  `name_group` VARCHAR(25) NULL,
  `password` VARCHAR(15) NOT NULL,
  `creator` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_user_group_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_user_group_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `aim`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aim`.`aim_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aim`.`aim_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_aim_id` INT NULL,
  `user_group_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aim_group_user_aim1_idx` (`user_aim_id` ASC),
  INDEX `fk_aim_group_user_group1_idx` (`user_group_id` ASC),
  CONSTRAINT `fk_aim_group_user_aim1`
    FOREIGN KEY (`user_aim_id`)
    REFERENCES `aim`.`user_aim` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aim_group_user_group1`
    FOREIGN KEY (`user_group_id`)
    REFERENCES `aim`.`user_group` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
